//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 29/01/2014 11:27:29 PM
namespace appSOA
{
    
    /// <summary>
    /// There are no comments for UPC2014Entities in the schema.
    /// </summary>
    public partial class UPC2014Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new UPC2014Entities object using the connection string found in the 'UPC2014Entities' section of the application configuration file.
        /// </summary>
        public UPC2014Entities() : 
                base("name=UPC2014Entities", "UPC2014Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UPC2014Entities object.
        /// </summary>
        public UPC2014Entities(string connectionString) : 
                base(connectionString, "UPC2014Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UPC2014Entities object.
        /// </summary>
        public UPC2014Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "UPC2014Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for INSCRIPCION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<INSCRIPCION> INSCRIPCION
        {
            get
            {
                if ((this._INSCRIPCION == null))
                {
                    this._INSCRIPCION = base.CreateQuery<INSCRIPCION>("[INSCRIPCION]");
                }
                return this._INSCRIPCION;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<INSCRIPCION> _INSCRIPCION;
        /// <summary>
        /// There are no comments for INSCRIPCION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToINSCRIPCION(INSCRIPCION iNSCRIPCION)
        {
            base.AddObject("INSCRIPCION", iNSCRIPCION);
        }
    }
    /// <summary>
    /// There are no comments for UPC2014Model.INSCRIPCION in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CodigoInscripcion
    /// DNI
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="UPC2014Model", Name="INSCRIPCION")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class INSCRIPCION : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new INSCRIPCION object.
        /// </summary>
        /// <param name="codigoInscripcion">Initial value of CodigoInscripcion.</param>
        /// <param name="dNI">Initial value of DNI.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static INSCRIPCION CreateINSCRIPCION(int codigoInscripcion, string dNI)
        {
            INSCRIPCION iNSCRIPCION = new INSCRIPCION();
            iNSCRIPCION.CodigoInscripcion = codigoInscripcion;
            iNSCRIPCION.DNI = dNI;
            return iNSCRIPCION;
        }
        /// <summary>
        /// There are no comments for property CodigoInscripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CodigoInscripcion
        {
            get
            {
                return this._CodigoInscripcion;
            }
            set
            {
                this.OnCodigoInscripcionChanging(value);
                this.ReportPropertyChanging("CodigoInscripcion");
                this._CodigoInscripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CodigoInscripcion");
                this.OnCodigoInscripcionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CodigoInscripcion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoInscripcionChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoInscripcionChanged();
        /// <summary>
        /// There are no comments for property DNI in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DNI
        {
            get
            {
                return this._DNI;
            }
            set
            {
                this.OnDNIChanging(value);
                this.ReportPropertyChanging("DNI");
                this._DNI = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DNI");
                this.OnDNIChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DNI;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDNIChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDNIChanged();
        /// <summary>
        /// There are no comments for property Tipo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this.OnTipoChanging(value);
                this.ReportPropertyChanging("Tipo");
                this._Tipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Tipo");
                this.OnTipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Tipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipoChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTipoChanged();
        /// <summary>
        /// There are no comments for property Nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for property ApellidoPaterno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ApellidoPaterno
        {
            get
            {
                return this._ApellidoPaterno;
            }
            set
            {
                this.OnApellidoPaternoChanging(value);
                this.ReportPropertyChanging("ApellidoPaterno");
                this._ApellidoPaterno = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ApellidoPaterno");
                this.OnApellidoPaternoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ApellidoPaterno;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidoPaternoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidoPaternoChanged();
        /// <summary>
        /// There are no comments for property ApellidoMaterno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ApellidoMaterno
        {
            get
            {
                return this._ApellidoMaterno;
            }
            set
            {
                this.OnApellidoMaternoChanging(value);
                this.ReportPropertyChanging("ApellidoMaterno");
                this._ApellidoMaterno = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ApellidoMaterno");
                this.OnApellidoMaternoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ApellidoMaterno;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidoMaternoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnApellidoMaternoChanged();
        /// <summary>
        /// There are no comments for property FechaInscripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaInscripcion
        {
            get
            {
                return this._FechaInscripcion;
            }
            set
            {
                this.OnFechaInscripcionChanging(value);
                this.ReportPropertyChanging("FechaInscripcion");
                this._FechaInscripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaInscripcion");
                this.OnFechaInscripcionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaInscripcion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaInscripcionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaInscripcionChanged();
        /// <summary>
        /// There are no comments for property Direccion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Direccion
        {
            get
            {
                return this._Direccion;
            }
            set
            {
                this.OnDireccionChanging(value);
                this.ReportPropertyChanging("Direccion");
                this._Direccion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Direccion");
                this.OnDireccionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Direccion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDireccionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDireccionChanged();
        /// <summary>
        /// There are no comments for property CodigoUbigeo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CodigoUbigeo
        {
            get
            {
                return this._CodigoUbigeo;
            }
            set
            {
                this.OnCodigoUbigeoChanging(value);
                this.ReportPropertyChanging("CodigoUbigeo");
                this._CodigoUbigeo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CodigoUbigeo");
                this.OnCodigoUbigeoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CodigoUbigeo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoUbigeoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCodigoUbigeoChanged();
    }
}
