#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using it.dominio;


namespace it.dominio	
{
	public partial class AlumnoPeriodo
	{
		private int _codigoAlumnoPeriodo;
		public virtual int CodigoAlumnoPeriodo 
		{ 
		    get
		    {
		        return this._codigoAlumnoPeriodo;
		    }
		    set
		    {
		        this._codigoAlumnoPeriodo = value;
		    }
		}
		
		private int _codigoPersona;
		public virtual int CodigoPersona 
		{ 
		    get
		    {
		        return this._codigoPersona;
		    }
		    set
		    {
		        this._codigoPersona = value;
		    }
		}
		
		private int _codigoPeriodo;
		public virtual int CodigoPeriodo 
		{ 
		    get
		    {
		        return this._codigoPeriodo;
		    }
		    set
		    {
		        this._codigoPeriodo = value;
		    }
		}
		
		private int _codigoSeccion;
		public virtual int CodigoSeccion 
		{ 
		    get
		    {
		        return this._codigoSeccion;
		    }
		    set
		    {
		        this._codigoSeccion = value;
		    }
		}
		
		private int? _estado;
		public virtual int? Estado 
		{ 
		    get
		    {
		        return this._estado;
		    }
		    set
		    {
		        this._estado = value;
		    }
		}
		
		private Alumno _alumno;
		public virtual Alumno Alumno 
		{ 
		    get
		    {
		        return this._alumno;
		    }
		    set
		    {
		        this._alumno = value;
		    }
		}
		
		private Periodo _periodo;
		public virtual Periodo Periodo 
		{ 
		    get
		    {
		        return this._periodo;
		    }
		    set
		    {
		        this._periodo = value;
		    }
		}
		
		private Seccion _seccion;
		public virtual Seccion Seccion 
		{ 
		    get
		    {
		        return this._seccion;
		    }
		    set
		    {
		        this._seccion = value;
		    }
		}
		
		private IList<Evaluacion> _evaluacions = new List<Evaluacion>();
		public virtual IList<Evaluacion> Evaluacions 
		{ 
		    get
		    {
		        return this._evaluacions;
		    }
		}
		
	}
}
