#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace it.dominio	
{
	public partial class CatalogoEstado
	{
		private int _codigoCatalogo;
		public virtual int CodigoCatalogo 
		{ 
		    get
		    {
		        return this._codigoCatalogo;
		    }
		    set
		    {
		        this._codigoCatalogo = value;
		    }
		}
		
		private int _valorCatalgo;
		public virtual int ValorCatalgo 
		{ 
		    get
		    {
		        return this._valorCatalgo;
		    }
		    set
		    {
		        this._valorCatalgo = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
	}
}
