#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace it.dominio	
{
	public partial class EvaluacionListarEntidad
	{
		private int _codigoEvaluacion;
		public virtual int CodigoEvaluacion 
		{ 
		    get
		    {
		        return this._codigoEvaluacion;
		    }
		    set
		    {
		        this._codigoEvaluacion = value;
		    }
		}
		
		private DateTime? _fecha;
		public virtual DateTime? Fecha 
		{ 
		    get
		    {
		        return this._fecha;
		    }
		    set
		    {
		        this._fecha = value;
		    }
		}
		
		private string _dNI;
		public virtual string DNI 
		{ 
		    get
		    {
		        return this._dNI;
		    }
		    set
		    {
		        this._dNI = value;
		    }
		}
		
		private string _alumno;
		public virtual string Alumno 
		{ 
		    get
		    {
		        return this._alumno;
		    }
		    set
		    {
		        this._alumno = value;
		    }
		}
		
		private string _evaluador;
		public virtual string Evaluador 
		{ 
		    get
		    {
		        return this._evaluador;
		    }
		    set
		    {
		        this._evaluador = value;
		    }
		}
		
		private string _respuesta;
		public virtual string Respuesta 
		{ 
		    get
		    {
		        return this._respuesta;
		    }
		    set
		    {
		        this._respuesta = value;
		    }
		}
		
		private string _observacion;
		public virtual string Observacion 
		{ 
		    get
		    {
		        return this._observacion;
		    }
		    set
		    {
		        this._observacion = value;
		    }
		}
		
	}
}
