#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using it.dominio;


namespace it.dominio	
{
	public partial class Inscripcion
	{
		private int _codigoInscripcion;
		public virtual int CodigoInscripcion 
		{ 
		    get
		    {
		        return this._codigoInscripcion;
		    }
		    set
		    {
		        this._codigoInscripcion = value;
		    }
		}
		
		private string _dNI;
		public virtual string DNI 
		{ 
		    get
		    {
		        return this._dNI;
		    }
		    set
		    {
		        this._dNI = value;
		    }
		}
		
		private int _tipo;
		public virtual int Tipo 
		{ 
		    get
		    {
		        return this._tipo;
		    }
		    set
		    {
		        this._tipo = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private string _apellidoMaterno;
		public virtual string ApellidoMaterno 
		{ 
		    get
		    {
		        return this._apellidoMaterno;
		    }
		    set
		    {
		        this._apellidoMaterno = value;
		    }
		}
		
		private string _apellidoPaterno;
		public virtual string ApellidoPaterno 
		{ 
		    get
		    {
		        return this._apellidoPaterno;
		    }
		    set
		    {
		        this._apellidoPaterno = value;
		    }
		}
		
		private DateTime _fechaInscripcion;
		public virtual DateTime FechaInscripcion 
		{ 
		    get
		    {
		        return this._fechaInscripcion;
		    }
		    set
		    {
		        this._fechaInscripcion = value;
		    }
		}
		
		private string _direccion;
		public virtual string Direccion 
		{ 
		    get
		    {
		        return this._direccion;
		    }
		    set
		    {
		        this._direccion = value;
		    }
		}
		
		private string _codigoUbigeo;
		public virtual string CodigoUbigeo 
		{ 
		    get
		    {
		        return this._codigoUbigeo;
		    }
		    set
		    {
		        this._codigoUbigeo = value;
		    }
		}
		
		private Ubigeo _ubigeo;
		public virtual Ubigeo Ubigeo 
		{ 
		    get
		    {
		        return this._ubigeo;
		    }
		    set
		    {
		        this._ubigeo = value;
		    }
		}
		
		private IList<InscripcionDetalle> _inscripcionDetalles = new List<InscripcionDetalle>();
		public virtual IList<InscripcionDetalle> InscripcionDetalles 
		{ 
		    get
		    {
		        return this._inscripcionDetalles;
		    }
		}
		
	}
}
