#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using it.dominio;


namespace it.dominio	
{
	public partial class Padre
	{
		private int _codigoPersona;
		public virtual int CodigoPersona 
		{ 
		    get
		    {
		        return this._codigoPersona;
		    }
		    set
		    {
		        this._codigoPersona = value;
		    }
		}
		
		private string _dNI;
		public virtual string DNI 
		{ 
		    get
		    {
		        return this._dNI;
		    }
		    set
		    {
		        this._dNI = value;
		    }
		}
		
		private string _direccion;
		public virtual string Direccion 
		{ 
		    get
		    {
		        return this._direccion;
		    }
		    set
		    {
		        this._direccion = value;
		    }
		}
		
		private string _codigoUbigeo;
		public virtual string CodigoUbigeo 
		{ 
		    get
		    {
		        return this._codigoUbigeo;
		    }
		    set
		    {
		        this._codigoUbigeo = value;
		    }
		}
		
		private int? _tipo;
		public virtual int? Tipo 
		{ 
		    get
		    {
		        return this._tipo;
		    }
		    set
		    {
		        this._tipo = value;
		    }
		}
		
		private Persona _persona;
		public virtual Persona Persona 
		{ 
		    get
		    {
		        return this._persona;
		    }
		    set
		    {
		        this._persona = value;
		    }
		}
		
		private Ubigeo _ubigeo;
		public virtual Ubigeo Ubigeo 
		{ 
		    get
		    {
		        return this._ubigeo;
		    }
		    set
		    {
		        this._ubigeo = value;
		    }
		}
		
	}
}
