#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using it.dominio;


namespace it.dominio	
{
	public partial class Perfil
	{
		private int _codigoPerfil;
		public virtual int CodigoPerfil 
		{ 
		    get
		    {
		        return this._codigoPerfil;
		    }
		    set
		    {
		        this._codigoPerfil = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private IList<Usuario> _usuarios = new List<Usuario>();
		public virtual IList<Usuario> Usuarios 
		{ 
		    get
		    {
		        return this._usuarios;
		    }
		}
		
	}
}
