#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using it.dominio;


namespace it.dominio	
{
	public partial class Seccion
	{
		private int _codigoSeccion;
		public virtual int CodigoSeccion 
		{ 
		    get
		    {
		        return this._codigoSeccion;
		    }
		    set
		    {
		        this._codigoSeccion = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private int _educacion;
		public virtual int Educacion 
		{ 
		    get
		    {
		        return this._educacion;
		    }
		    set
		    {
		        this._educacion = value;
		    }
		}
		
		private IList<InscripcionDetalle> _inscripcionDetalles = new List<InscripcionDetalle>();
		public virtual IList<InscripcionDetalle> InscripcionDetalles 
		{ 
		    get
		    {
		        return this._inscripcionDetalles;
		    }
		}
		
		private IList<AlumnoPeriodo> _alumnoPeriodos = new List<AlumnoPeriodo>();
		public virtual IList<AlumnoPeriodo> AlumnoPeriodos 
		{ 
		    get
		    {
		        return this._alumnoPeriodos;
		    }
		}
		
	}
}
