#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using it.dominio;


namespace it.dominio	
{
	public partial class Ubigeo
	{
		private string _codigoUbigeo;
		public virtual string CodigoUbigeo 
		{ 
		    get
		    {
		        return this._codigoUbigeo;
		    }
		    set
		    {
		        this._codigoUbigeo = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private IList<Padre> _padres = new List<Padre>();
		public virtual IList<Padre> Padres 
		{ 
		    get
		    {
		        return this._padres;
		    }
		}
		
		private IList<Inscripcion> _inscripcions = new List<Inscripcion>();
		public virtual IList<Inscripcion> Inscripcions 
		{ 
		    get
		    {
		        return this._inscripcions;
		    }
		}
		
	}
}
