#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using it.dominio;


namespace it.dominio	
{
	public partial class Usuario
	{
		private int _codigoUsuario;
		public virtual int CodigoUsuario 
		{ 
		    get
		    {
		        return this._codigoUsuario;
		    }
		    set
		    {
		        this._codigoUsuario = value;
		    }
		}
		
		private string _nombre;
		public virtual string Nombre 
		{ 
		    get
		    {
		        return this._nombre;
		    }
		    set
		    {
		        this._nombre = value;
		    }
		}
		
		private string _contrasenia;
		public virtual string Contrasenia 
		{ 
		    get
		    {
		        return this._contrasenia;
		    }
		    set
		    {
		        this._contrasenia = value;
		    }
		}
		
		private int _codigoPersona;
		public virtual int CodigoPersona 
		{ 
		    get
		    {
		        return this._codigoPersona;
		    }
		    set
		    {
		        this._codigoPersona = value;
		    }
		}
		
		private Persona _persona;
		public virtual Persona Persona 
		{ 
		    get
		    {
		        return this._persona;
		    }
		    set
		    {
		        this._persona = value;
		    }
		}
		
		private IList<Perfil> _perfils = new List<Perfil>();
		public virtual IList<Perfil> Perfils 
		{ 
		    get
		    {
		        return this._perfils;
		    }
		}
		
		private IList<Evaluacion> _evaluacions = new List<Evaluacion>();
		public virtual IList<Evaluacion> Evaluacions 
		{ 
		    get
		    {
		        return this._evaluacions;
		    }
		}
		
	}
}
